# Generated by Django 4.2.3 on 2023-07-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="department")),
            ],
            options={
                "verbose_name": "department",
                "verbose_name_plural": "departments",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("T", "Transgender"),
                            ("Do not wish to disclose", "Do not wish to disclose"),
                        ],
                        max_length=30,
                    ),
                ),
                ("phone", models.IntegerField()),
                ("mail_id", models.EmailField(max_length=250, unique=True)),
                ("address", models.TextField()),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("General Sciences", "General Sciences"),
                            ("Commerce", "Commerce"),
                            ("Arts", "Arts"),
                            ("Astronomy", "Astronomy"),
                            ("Computer Science", "Computer Science"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("Enquiry", "For Enquiry"),
                            ("Order", "To Place Order"),
                            ("Return", "Return"),
                        ],
                        max_length=20,
                    ),
                ),
                ("materials", models.BooleanField()),
            ],
        ),
    ]
